services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fortune-server
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    volumes:
      - ./logs:/app/logs
      - ./certs:/app/certs

  mongo:
    image: mongo:6.0
    container_name: fortune-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7.2-alpine
    container_name: fortune-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
